import { X, AlertTriangle } from "lucide-react";
import { useSEO } from "../hooks/useSEO";
import "./css/Legal.css";

export default function Disclaimer({ onClose }) {
  useSEO({
    title: "Disclaimer - Tools Cli",
    description: "Read the important disclaimers and liability information regarding the use of commands generated by Tools Cli.",
    path: "disclaimer"
  });

  return (
    <div className="legal-container">
      <div className="legal-header">
        <div className="legal-title-section">
          <h1>Disclaimer</h1>
          <div className="legal-last-updated">Last Updated: September 8, 2026</div>
        </div>
        <button
          className="close-btn"
          onClick={onClose}
          aria-label="Close Disclaimer"
        >
          <X size={20} />
        </button>
      </div>

      <div className="legal-content">
        <div className="legal-highlight-box">
          <p>
            Please read the following disclaimer carefully before using the tools and commands provided on this website.
          </p>
        </div>

        <section className="legal-section">
          <h2>
            <AlertTriangle size={18} /> 1. Educational and Informational Purposes Only
          </h2>
          <p>
            The content, command-line snippets, and interactive builders provided on tools-cli.konshu.in are for educational and informational purposes only. While we strive to keep the information accurate and up-to-date, we make no representations or warranties of any kind regarding the accuracy, completeness, or reliability of the generated commands.
          </p>
        </section>

        <section className="legal-section">
          <h2>
            <AlertTriangle size={18} /> 2. No Liability for Damages
          </h2>
          <p>
            Command-Line Interface (CLI) operations can directly affect your system, files, and servers. By using this website, you agree that the creator(s) and maintainers of tools-cli.konshu.in shall not be held liable for any data loss, system damage, security breaches, or other negative consequences resulting from executing the commands generated here. Always review and understand a command before running it in your terminal.
          </p>
        </section>

        <section className="legal-section">
          <h2>
            <AlertTriangle size={18} /> 3. Copyright and Third-Party Media (yt-dlp, FFmpeg)
          </h2>
          <p>
            Tools referenced on this site, such as yt-dlp and FFmpeg, are powerful utilities meant for processing media that you legally own or have explicit permission to modify/download. You are solely responsible for complying with the Terms of Service of third-party websites (e.g., YouTube, Vimeo) and all applicable copyright laws. We strictly condemn piracy and do not endorse the unauthorized downloading or distribution of copyrighted material.
          </p>
        </section>

        <section className="legal-section">
          <h2>
            <AlertTriangle size={18} /> 4. Trademarks and Non-Affiliation
          </h2>
          <p>
            All product names, logos, and brands mentioned on this website (including but not limited to Git, Ollama, Vercel, Google Gemini, Node.js, and Android) are the property of their respective trademark holders. tools-cli.konshu.in is an independent, community-driven, open-source project and is not affiliated with, endorsed by, or sponsored by any of these companies or organizations.
          </p>
        </section>
      </div>
    </div>
  );
}
